FROM mcr.microsoft.com/dotnet/core/sdk:2.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["slmspKubernetesContainerApplication/slmspKubernetesContainerApplication.csproj", "slmspKubernetesContainerApplication/"]

RUN dotnet restore "slmspKubernetesContainerApplication/slmspKubernetesContainerApplication.csproj"
COPY . .
WORKDIR "/src/slmspKubernetesContainerApplication"
RUN dotnet build --no-restore "slmspKubernetesContainerApplication.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]